### ISSUE TITLE
Add step to prevent FM breakage

### ISSUE THREAD

**Issue by Skibicki** [sungaila/NewDarkGlobalServer#1]
The multiplayer component causes some fan missions to break. There is a workaround for this, but for simplicity the readme file should advise users to keep a separate Thief folder for multiplayer.
https://www.ttlg.com/forums/showthread.php?t=150172&p=2433328&viewfull=1#post2433328

**Comment by sungaila** [comment]
Hi @Skibicki, thanks for bringing this to my attention! I've added this line into the readme:

> Note: A few fan missions will not work after installing the multiplayer patch. So consider to create a copy of the Thief 2 game folder for singleplayer purposes.

This should inform anyone about the potential break of fan missions without exaggerating the severity of this problem.

While the purpose of this readme is about configuring the global server, I'm still happy people can use it as a guide for setting up the T2 multiplayer itself. :-)
